apiVersion: v1
kind: Pod
metadata:
  name: secret-reader
  labels:
    name: secret-reader
spec:
  serviceAccountName: default
  containers:
  - name: secret-reader
    image: docker.io/ashishmahawal/read-secret:1.0.0
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
