---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-read
rules:
- apiGroups: [""]
  resources: ["Secret"]
  verbs: ["get,list,watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-read